---
abstract: 'OO Interface for the REST services provided by Atlassian Bamboo'
author:
  - 'Mike Eldridge <diz@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Bamboo
requires:
  DateTimeX::Easy: 0.089
  IO::File: 0.14
  Moose: 2.00
  MooseX::Types::URI: 0.02
  XML::Tidy: 1.12
  XML::XPath: 1.13
version: 0.01
